[package]
name = "ais-schema"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
ais-core = { path = "../ais-core" }
serde_json.workspace = true
jsonschema.workspace = true
